### ISSUE TITLE
Feature Request: Allow for single drive installation to house OS and Data

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/simpnas#23]
Allow for single drive installation to house OS and Data

**Comment by johnnyq** [comment]
f1e11674f45b8a84449b4a2627245ecbb09eb70a

635a3b5d7b300b66b337f9cc13649d3c070044ee

**Comment by tido-** [comment]
You are very flexible and implement many ideas (everybody darling), however, I think it is worth the time to write down some technical 'boundaries' and make these public in order to not jump left, right and center.
From your README "similar to OpenMediaVault, UnRAID and FreeNAS, but with a much more simpler approach."
FreeNAS for example keeps the OS-Drive exclusive for that. 

- Now S-NAS could be easier in that regard and just insist on a partition but then, what is the minimum size? 
Keep space for all possibly installable Apps? 
- What space needs the chatty Home Assistant? 
Will the log fill up too fast, system breaks == bad user experience.

Just as an idea.

**Comment by johnnyq** [comment]
Thanks @tido- =]
 Good ideas i will start making a list!
